name: Registry login

on:
  workflow_dispatch:

jobs:
  build:
    name: Registry login
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker
        uses: docker/login-action@v3
        with:
          registry: reg.vnuchkov.su
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
